name: Node CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run export

      - name: Create separated builds
        run: node build

      - name: Upload windows build
        uses: actions/upload-artifact@v1
        with:
          name: vk-phishing-win
          path: ./build/windows

      - name: Upload unix build
        uses: actions/upload-artifact@v1
        with:
          name: vk-phishing-unix
          path: ./build/unix

      - name: Upload docker build
        uses: actions/upload-artifact@v1
        with:
          name: vk-phishing-docker
          path: ./build/docker

      - name: Upload external build
        uses: actions/upload-artifact@v1
        with:
          name: external
          path: ./build/external
